# Copyright (c) 2021 Changkun Ou <hi@changkun.de>. All Rights Reserved.
# Unauthorized using, copying, modifying and distributing, via any
# medium is strictly prohibited.

FROM alpine
WORKDIR /app
COPY . .
EXPOSE 80
CMD ["/app/void", "serv"]